"""Build the Lesser Feasts and Fasts + Marriage/Burial data modules.

Usage: python3 build_extra.py <cache dir>
Needs <cache>/lff/ (index + Marriage/Burial pages), <cache>/lffpg/ (commemoration pages) — see fetch.sh.
Writes src/data/episcopalLesserFeasts.js and src/data/episcopalSpecial.js (citations only).
"""
import html, json, os, re, subprocess, sys
import common
from common import clean_ref, build_set, psalm_text_ref

CACHE = sys.argv[1]
common.load_vanderbilt(CACHE)
HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, '..', '..', 'src', 'data')

def txt(x): return re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', x))).strip()
MONTHS = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

# ── Lesser Feasts and Fasts ──────────────────────────────────────────────────
# parse.py has already turned <cache>/lffpg/*.html into lff_raw.json (references per page)
raw = json.load(open(os.path.join(CACHE, 'lff_raw.json')))
idx = open(os.path.join(CACHE, 'lff', 'CalndrsIndexes_TxtIndexLFF.html'), encoding='utf-8', errors='ignore').read()

feasts = {}
parts = re.split(r'<h3(?: style="margin-left: 40px;")?>(' + '|'.join(MONTHS) + r')</h3>', idx)
for mi in range(1, len(parts), 2):
    month = MONTHS.index(parts[mi]) + 1
    for li in re.finditer(r'<li>(.*?)</li>', parts[mi + 1], re.S):
        body = li.group(1)
        dm = re.match(r'\s*\[?\s*(\d+)', txt(body))
        a = re.search(r'<a href="\.\./(LesserFF/[^"]+)">(.*?)</a>(.*)$', body, re.S)
        if not dm or not a: continue
        page = a.group(1)[:-5].replace('/', '_')
        if page not in raw: print('no page for', page); continue
        trial = '[' in body[:body.find('<a')]
        name = txt(a.group(2)); sub = txt(a.group(3)).lstrip(', ').strip(' ]')
        key = 'LFF.' + page.replace('LesserFF_', '')
        f = feasts.setdefault(key, {'name': name, 'sub': sub, 'dates': [], 'readings': build_set(raw[page]['items'], 1)})
        md = f'{month:02d}-{int(dm.group(1)):02d}'
        if md not in f['dates']: f['dates'].append(md)
        if trial: f['trial'] = True
print('lesser feasts:', len(feasts))
json.dump(feasts, open('built_lff.json', 'w'), indent=1)
open(os.path.join(DATA, 'episcopalLesserFeasts.js'), 'w').write(
    '// GENERATED by scripts/episcopal/build_extra.py — do not edit by hand.\n'
    '// Lesser Feasts and Fasts 2022 with the 2024 General Convention lectionary — lesson citations only,\n'
    '// from The Lectionary Page (lectionarypage.net). `dates` are MM-DD; `trial` = approved for trial use.\n\n'
    'export const EPISCOPAL_LESSER_FEASTS = ' + json.dumps(feasts, indent=1, ensure_ascii=False) + '\n')

# ── Marriage and Burial (BCP lists of lessons) ───────────────────────────────
def page_text(name):
    s = open(os.path.join(CACHE, 'lff', name), encoding='utf-8', errors='ignore').read()
    return re.sub(r'\s+', ' ', html.unescape(re.sub(r'<[^>]+>', ' ', s)))

OT = {'Genesis', 'Song of Solomon', 'Tobit', 'Isaiah', 'Lamentations', 'Wisdom', 'Wisdom of Solomon', 'Job', 'Daniel', 'Ecclesiasticus', 'Sirach'}
GOSPEL = {'Matthew', 'Mark', 'Luke', 'John'}
ENTRY = re.compile(r"((?:\d )?[A-Z][a-z]+(?: of [A-Z][a-z]+)?) (\d[\d:,\-;\s\[\]a-c]*?)\s*(?:\(_[^)]*_\)\s*)?\(((?:[^()]|\([^()]*\))*)\)")

def section(book):
    return 'oldTestament' if book in OT else 'gospels' if book in GOSPEL and True else 'newTestament'

def readings_list(text, tag, eow=False):
    out = {'oldTestament': [], 'psalms': [], 'newTestament': [], 'gospels': []}
    for m in ENTRY.finditer(text):
        book, spec, desc = m.group(1), m.group(2).strip(' ,;'), re.sub(r'\s+', ' ', m.group(3)).strip()
        ref = clean_ref(f'{book} {spec}')
        sec = section(book)
        # 1 John is an epistle, not the Gospel of John
        if book == 'John' and False: pass
        out[sec].append({'ref': ref, 'label': desc})
    return out

def psalm_options(chunk):
    # "42:1-7 , 46 , 90:1-12 , 121 ." — the links leave spaces around the separating commas
    refs = []
    for tok in re.split(r'\s+,\s+|\s+and\s+', chunk.strip(' .*,')):
        tok = re.sub(r'^and\s+', '', tok.strip()).replace('Psalm', '').strip(' .*,')
        if re.match(r'^\d{1,3}(:[\d\-, ]+)?$', tok): refs.append(clean_ref('Psalm ' + tok))
    return refs

def build_special(page, tag):
    t = page_text(page)
    if tag == 'marriage':
        body = t[t.index('One or more of the following'):t.index('Genesis 1:26-28 God said')]
        pchunk = body[body.index('Appropriate Psalms'):body.index('Matthew 5:1-10')]
        lists = readings_list(body.replace(pchunk, ' '), tag)
        psalms = psalm_options(pchunk.replace('Appropriate Psalms are', ''))
    else:
        start = t.index('From the Old Testament')
        end = t.index('These texts are also available')
        body = t[start:end]
        pchunks = re.findall(r'are appropriate:\s*(.*?)\s+\.\s', body + ' ')
        lists = readings_list(re.sub(r'A suitable psalm.*?are appropriate:.*?\s\.\s', ' ', body), tag)
        psalms = [p for c in pchunks for p in psalm_options(c)]
    return lists, psalms

def finish(lists, psalms, extra_labels=None):
    seen = set(); ps = []
    for p in psalms:
        if p in seen: continue
        seen.add(p); ps.append({'ref': p, 'label': 'Psalm ' + p.split(' ', 1)[1]})
    lists['psalms'] = ps
    for sec, opts in lists.items():
        for o in opts:
            tr = psalm_text_ref(o['ref']) if o['ref'].startswith('Psalm') else None
            if tr: o['textRef'] = tr
    return lists

marriage, mpsalms = build_special('YearABC_SpecServ_Marriage.html', 'marriage')
burial, bpsalms = build_special('YearABC_SpecServ_Burial.html', 'burial')
# Enriching Our Worship 3 burial lessons are additional choices
eow, epsalms = build_special('YearABC_SpecServ_BurialEOW3.html', 'burial')
for sec in ('oldTestament', 'newTestament', 'gospels'):
    have = {o['ref'] for o in burial[sec]}
    burial[sec] += [dict(o, label=o['label'] + ' · Enriching Our Worship 3') for o in eow[sec] if o['ref'] not in have]
bpsalms += epsalms
special = {'marriage': finish(marriage, mpsalms), 'burial': finish(burial, bpsalms)}
for k, v in special.items(): print(k, {s: len(o) for s, o in v.items()})
json.dump(special, open('built_special.json', 'w'), indent=1)
open(os.path.join(DATA, 'episcopalSpecial.js'), 'w').write(
    '// GENERATED by scripts/episcopal/build_extra.py — do not edit by hand.\n'
    '// Lessons for the Celebration and Blessing of a Marriage and the Burial of the Dead (BCP lists, plus the\n'
    '// Enriching Our Worship 3 burial lessons). Shape matches WEDDING_READINGS / FUNERAL_READINGS.\n\n'
    'export const EPISCOPAL_MARRIAGE = ' + json.dumps(special['marriage'], indent=1, ensure_ascii=False) + '\n\n'
    'export const EPISCOPAL_BURIAL = ' + json.dumps(special['burial'], indent=1, ensure_ascii=False) + '\n')
