// Dev seed — used only in development via ?seed=N URL param
// ?seed=6  → Workshop step (Heart sections)   [was step 7]
// ?seed=7  → Preach step (three paths)         [was step 8]

export const seeds = {
  6: {
    date: '2025-03-09',
    tradition: 'Catholic',
    occasion: 'Sunday Mass',
    liturgicalSeason: 'Lent',
    sundayName: 'First Sunday of Lent',
    liturgicalYear: 'C',
    readings: [
      { id: 'first', label: 'First Reading', reference: 'Deuteronomy 26:4-10', translation: 'NABRE', text: 'Moses spoke to the people, saying: "The priest shall receive the basket from you and shall set it in front of the altar of the LORD, your God."' },
      { id: 'psalm', label: 'Psalm', reference: 'Psalm 91:1-2, 10-15', translation: 'NABRE', text: 'You who dwell in the shelter of the Most High, who abide in the shadow of the Almighty...' },
      { id: 'gospel', label: 'Gospel', reference: 'Luke 4:1-13', translation: 'NABRE', text: 'Filled with the Holy Spirit, Jesus returned from the Jordan and was led by the Spirit into the desert for forty days, to be tempted by the devil.' },
    ],
    selectedReadings: { first: true, psalm: true, second: false, gospel: true },
    lectioNotes: {
      lectio: 'Filled with the Holy Spirit — Jesus returns from baptism immediately into the wilderness.',
      meditatio: 'The Spirit leads Jesus into temptation, not away from it. The desert is part of the plan.',
      oratio: 'Lord, help me trust that the hard seasons are not punishment but preparation.',
      contemplatio: 'Sitting with the image of Jesus hungry, alone, and still unbroken.',
      theTurn: 'I assumed this text was about resisting evil. But sitting with it, I think it\'s actually about identity — the devil keeps saying "If you are the Son of God..." as if Jesus needs to prove it. The temptation is to perform, not to sin.',
    },
    personalStory: 'Last February I drove through a blizzard to visit my father in the hospital. The roads were empty — just me and the white. I remember thinking: this is wrong, I shouldn\'t be out here alone. And then I thought: he\'s alone too.',
    storyConnection: 'That feeling of being stripped of every comfort is exactly what Lent asks of us.',
    congregationMoment: 'Elena, who sits near the back and lost her job three weeks ago. She smiled during the sign of peace but her eyes were somewhere else.',
    homilyAim: {
      action: 'leave knowing that their desert season is not abandonment — it is appointment',
      because: 'the same Spirit who led Jesus into the wilderness is leading them',
    },
    synthesis: {
      selectedTheme: 'Wilderness / Desert',
      themeStatement: 'This homily is really about how God meets us precisely in the places we\'d rather not be.',
      coreInsight: 'The Spirit does not protect Jesus from the desert — the Spirit leads him there. The wilderness is not abandonment. It is appointment.',
      congregationNeed: 'Many people in this parish are in their own desert right now — grief, illness, uncertainty. They need permission to see that season as sacred, not as failure.',
      verbumClips: [
        {
          headline: 'πειράζω — to test, not merely tempt',
          keyword: 'tempt',
          body: 'The Greek peirazō carries the sense of testing for genuineness — the same word used when God tested Abraham. The desert is a crucible, not a punishment.',
          source: 'Louw-Nida Greek Lexicon',
          type: 'language',
        },
        {
          headline: 'Augustine: the desert as place of hearing',
          keyword: 'desert',
          body: 'Augustine notes that the desert of Scripture is always a place of hearing — Elijah, Moses, John the Baptist, now Jesus. Silence creates the conditions for the Word.',
          source: 'De Doctrina Christiana',
          type: 'patristic',
        },
      ],
    },
    tone: 'pastoral',
    theme: 'Wilderness / Desert',
    audience: 'parish',
    currentEvents: 'Many families in our area are facing layoffs after the plant closure. There\'s a real undercurrent of fear about the future.',
    missionFocus: 'Name one person in your life who is in their own desert right now. Reach out to them this week — not to fix it, just to say: I see you.',
    framework: {
      openingStory: '',
      preview: '',
      gospelAnchor: '',
      gospelInsight: '',
      gospelBridge: '',
      mission: '',
      closeLoop: '',
    },
    finalHomily: '',
    homilyPath: '',
    currentStep: 6,
    completedSteps: [1, 2, 3, 4, 5],
  },
  7: {
    date: '2025-03-09',
    tradition: 'Catholic',
    occasion: 'Sunday Mass',
    liturgicalSeason: 'Lent',
    sundayName: 'First Sunday of Lent',
    liturgicalYear: 'C',
    readings: [
      { id: 'first', label: 'First Reading', reference: 'Deuteronomy 26:4-10', translation: 'NABRE', text: 'Moses spoke to the people, saying: "The priest shall receive the basket from you."' },
      { id: 'gospel', label: 'Gospel', reference: 'Luke 4:1-13', translation: 'NABRE', text: 'Filled with the Holy Spirit, Jesus returned from the Jordan and was led by the Spirit into the desert for forty days, to be tempted by the devil.' },
    ],
    selectedReadings: { first: true, psalm: true, second: false, gospel: true },
    lectioNotes: {
      lectio: 'Filled with the Holy Spirit — Jesus returns from baptism immediately into the wilderness.',
      meditatio: 'The Spirit leads Jesus into temptation, not away from it.',
      oratio: 'Lord, help me trust that the hard seasons are not punishment but preparation.',
      contemplatio: 'Sitting with the image of Jesus hungry, alone, and still unbroken.',
      theTurn: 'I assumed this text was about resisting evil. But sitting with it, I think it\'s actually about identity — the devil keeps saying "If you are the Son of God..." The temptation is to perform, not to sin.',
    },
    personalStory: 'Last February I drove through a blizzard to visit my father in the hospital. The roads were empty — just me and the white. I remember thinking: this is wrong. And then I thought: he\'s alone too.',
    storyConnection: 'That feeling of being stripped of every comfort is exactly what Lent asks of us.',
    congregationMoment: 'Elena, who sits near the back and lost her job three weeks ago. She smiled during the sign of peace but her eyes were somewhere else.',
    homilyAim: {
      action: 'leave knowing that their desert season is not abandonment — it is appointment',
      because: 'the same Spirit who led Jesus into the wilderness is leading them',
    },
    synthesis: {
      selectedTheme: 'Wilderness / Desert',
      themeStatement: 'This homily is really about how God meets us precisely in the places we\'d rather not be.',
      coreInsight: 'The Spirit does not protect Jesus from the desert — the Spirit leads him there.',
      congregationNeed: 'Many people in this parish are in their own desert right now — grief, illness, uncertainty.',
      verbumClips: [
        {
          headline: 'πειράζω — to test, not merely tempt',
          keyword: 'tempt',
          body: 'The Greek peirazō carries the sense of testing for genuineness. The desert is a crucible, not a punishment.',
          source: 'Louw-Nida Greek Lexicon',
          type: 'language',
        },
      ],
    },
    tone: 'pastoral',
    theme: 'Wilderness / Desert',
    audience: 'parish',
    currentEvents: 'Many families in our area are facing layoffs after the plant closure.',
    missionFocus: 'Name one person in your life who is in their own desert right now. Reach out this week.',
    framework: {
      openingStory: 'Last February I drove through a blizzard to visit my father in the hospital. The roads were completely empty — just me and the white. I remember thinking: this is wrong, I shouldn\'t be out here alone. And then I thought: he\'s alone too.',
      preview: 'This Lent, I want to ask you something that might feel uncomfortable: what if the hard place you\'re in right now is exactly where God wants to find you?',
      gospelAnchor: 'The Spirit does not protect Jesus from the desert. The Spirit leads him there.',
      gospelInsight: 'The Greek word translated "tempted" — peirazō — carries the sense of testing for genuineness. It\'s the same word used when God tested Abraham. The desert is not punishment. It is appointment.',
      gospelBridge: 'Many of you are in a desert right now. The plant closure. The diagnosis. The marriage that went quiet. The faith that stopped feeling like anything. Lent gives us permission to call that season by its right name — and to trust it.',
      mission: 'Think of one person in your life who is in their own wilderness right now. Not someone you can fix. Just someone you can see. Reach out this week — a text, a call, a knock on the door — and say: I see you.',
      closeLoop: 'The road through the blizzard was empty. But it wasn\'t abandoned.',
    },
    finalHomily: '',
    homilyPath: '',
    currentStep: 7,
    completedSteps: [1, 2, 3, 4, 5, 6],
  },
}
